# Generated by Django 5.0.6 on 2024-05-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qiziqishi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
