# Generated by Django 5.0.6 on 2024-05-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_qiziqishi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interests',
        ),
    ]
