# Generated by Django 5.0.6 on 2024-05-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_occupation',
        ),
    ]
