# Generated by Django 5.0.6 on 2024-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_current_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='sertificates/'),
        ),
    ]
