# Generated by Django 5.0.6 on 2024-05-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmaps',
            name='body',
        ),
    ]
