# Generated by Django 5.0.6 on 2024-05-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_roadmaps_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='url',
            field=models.URLField(),
        ),
    ]
