# Generated by Django 5.0.6 on 2024-05-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('first', models.TextField(blank=True, null=True)),
                ('second', models.TextField(blank=True, null=True)),
                ('third', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
