# Generated by Django 5.0.6 on 2024-05-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai',
            name='first',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai',
            name='second',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ai',
            name='third',
            field=models.TextField(blank=True, null=True),
        ),
    ]
