# Generated by Django 5.0.6 on 2024-06-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
