# Generated by Django 5.0.6 on 2024-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_text_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='system',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
